src/Entity/Spectacle.php
<?php

namespace App\Entity;

use App\Repository\SpectacleRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SpectacleRepository::class)]
class Spectacle
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\ManyToOne(inversedBy: 'spectacles')]
    private ?Lieu $Lieu = null;

    /**
     * @param int|null $id
     * @param string|null $nom
     * @param string|null $description
     * @param string|null $image
     * @param int|null $Lieu
     * @param \DateTimeInterface|null $date
     */
    public function __construct(?string $nom, ?string $description, ?string $image, ?\DateTimeInterface $date, ?int $Lieu)
    {
        $this->nom = $nom;
        $this->description = $description;
        $this->image = $image;
        $this->date = $date;
        $this->Lieu = $Lieu;
    }

    /**
     * @param string|null $nom
     */


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function __toString(): string
    {
        return $this->getNom();
    }

    public function getLieu(): ?Lieu
    {
        return $this->Lieu;
    }

    public function setLieu(?Lieu $Lieu): static
    {
        $this->Lieu = $Lieu;

        return $this;
    }

}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Entity\Spectacle;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    #[Route('/', name: 'app_homepage')]
    public function index(): Response
    {
        return $this->render('default/index.html.twig', [
        ]);
    }
    #[Route('/spectacle/test', name: 'app_spectacle')]
    public function testSpectacle(): Response
    {
        $spec1 = new Spectacle("Cabaret","Venez assistez au plus grand cabaret du monde","images/1.jpg", new \DateTime('now'),null);
        return $this->render('default/spectacleTest.html.twig', [
            'spectacleTest' => $spec1,
        ]);
    }


}

templates/default/Lieu.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <table>
        <tr class="Spectacle_infoTable">
            <td>&nbsp;</td>
            <td>Nom Lieu</td>
            <td>Adresse</td>
            <td>code_postal</td>
            <td>Ville</td>
        </tr>
        <tr>
            {% for Lieubd in Lieu %}
            <td>&nbsp;</td>
            <td>{{ Lieubd.nom }}</td>
            <td>{{ Lieubd.adresse }}</td>
            <td>
                {{ Lieubd.codePostal }}
            </td>
            <td>{{ Lieubd.ville }}</td>
        </tr>
        {% endfor %}

    </table>

{% endblock %}

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DefaultController!{% endblock %}

{% block body %}

    </header>
    <main>
        <h2>Suivez les instructions du TP</h2>>
    </main>
    <footer>
        <p>Année Universitaire 2023 | 2024 - LPMiaw</p>
    </footer>
{% endblock %}

templates/default/spectacle.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <table>
        <tr class="Spectacle_infoTable">
            <td>&nbsp;</td>
            <td>Nom Evement</td>
            <td>description</td>
            <td>image</td>
            <td>date</td>
            <td>Lieu</td>
        </tr>
        <tr>
            {% for spec in Spectacles %}
            <td>&nbsp;</td>
            <td>{{ spec.nom }}</td>
            <td>{{ spec.description }}</td>
            <td>
                <img src="{{ asset(spec.image) }}">
            </td>
            <td>{{ spec.date|date('Y-m-d') }}</td>
            {% if spec.lieu is not null %}
            <td>{{ spec.lieu.nom}}</td>
                {% else %}
                    <td>Aucun lieu trouvé</td>
            {% endif %}

        </tr>
        {% endfor %}

    </table>

{% endblock %}

templates/default/spectacleTest.html.twig
{% extends 'base.html.twig' %}
{% block title %}Spectacle{% endblock %}

{% block body %}
    {{ spectacleTest.nom }} : {{ spectacleTest.description }}
    <img src="{{ asset(spectacleTest.image) }}">
{% endblock %}